routes/web.php
<?php

Route::get("/", "LandingController@getLanding")->name("landing");

Route::get("/user/{name}", "PhotoItemController@getProfile")->name("profile");
Route::get("/user/{name}/{photo_id}", "PhotoItemController@getPhoto")->name("photo");

Route::get("/search", "SearchController@getSearch")->name("search");
Route::get("/search/{query}", "SearchController@getSearchResults")->name("results");

Route::middleware(["guest"])->group(function() {
	Route::get("/signup", "Authentication\SignupController@getForm")->name("signup.form");
	Route::post("/signup", "Authentication\SignupController@attemptAction")->name("signup.attempt");
	Route::get("/login", "Authentication\LoginController@getForm")->name("login.form");
	Route::post("/login", "Authentication\LoginController@attemptAction")->name("login.attempt");
});

Route::middleware(["auth"])->group(function() {
	Route::post("/logout", "Authentication\LogoutController@attemptAction")->name("logout.attempt");

	Route::get("/dashboard", "DashboardController@getDashboard")->name("dashboard");

	Route::get("/dashboard/photos", "PhotoListController@getDefaultView")->name("photos");
	Route::get("/dashboard/photos/grid", "PhotoListController@getGrid")->name("photos.grid");
	Route::get("/dashboard/photos/table", "PhotoListController@getTable")->name("photos.table");

	Route::get("/dashboard/photo", "PhotoManagementController@getUploadForm")->name("photo.upload.form");
	Route::post("/dashboard/photo", "PhotoManagementController@postPhoto")->name("photo.upload.post");
	Route::post("/dashboard/photo/{id}", "PhotoManagementController@postPhotoData")->name("photo.edit.post");
	Route::delete("/dashboard/photo/{id}", "PhotoManagementController@deletePhoto")->name("photo.delete");

	Route::get("/dashboard/tags/search", "TagController@allTags")->name("tag.all");
	Route::get("/dashboard/tags/search/{query}", "TagController@searchTags")->name("tag.search");
});

app/Models/Photo.php
<?php

namespace Photogram\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsToMany as BelongsToManyRelation;
use Illuminate\Database\Eloquent\Relations\BelongsTo as BelongsToRelation;

class Photo extends Model {

	const DESCRIPTION_TRIM_LIMIT = 144;

	protected $fillable = ["user_id", "description", "file", "is_public", "tags"];
	protected $visible = ["id", "description", "file", "is_public", "tags"];
	protected $casts = [
		"is_public" => "boolean",
		"tags" => "array"
	];

	protected static function boot() {
		parent::boot();

		static::addGlobalScope("public", function(Builder $builder) {
			$builder->where("is_public", true);
		});
	}

	public function user(): BelongsToRelation {
		return $this->belongsTo(User::class);
	}

	public function tags(): BelongsToManyRelation {
		return $this->belongsToMany(Tag::class)->orderBy("name");
	}

	public function getFilePathAttribute(): string {
		return asset("storage/photos/" . $this->file);
	}

	public function getUploadedAttribute(): string {
		return $this->created_at->diffForHumans();
	}

	public function getTrimmedDescriptionAttribute(): string {
		return mb_strimwidth($this->description, 0, self::DESCRIPTION_TRIM_LIMIT, "...");
	}

}

resources/views/photos/edit.blade.php
@extends("layout/dashboard")

@section("dashboard-content")

	<upload-photo-form attempt-url="{{ route("photo.upload.post") }}"></upload-photo-form>

@endsection

resources/views/photos/grid.blade.php
@extends("layout/dashboard")

@section("dashboard-content")

	<div class="ui switch layout segment clearing">
		<a href="{{ route("photos.table") }}" class="ui labeled icon right floated button">
			<i class="list layout icon"></i>
			switch do table view
		</a>
	</div>

	<div class="ui centered cards">
		<div class="card">
			<div class="image">
				<img src="{{ asset('images/blank.png') }}">
			</div>
			<div class="content">
				<div class="limited description">
					Choose the greatest photo from your hard drive, write a breathtaking description, set picture as private or public and attach some popular tags. It's that simple!
				</div>
			</div>
			<div class="extra content">
				<div class="right floated">
					<span>now</span>
				</div>
			</div>
			<a href="{{ route("photo.upload.form") }}" class="ui bottom attached green button">
				<i class="add icon"></i>
				add
			</a>
		</div>
		@foreach($photos as $photo)
			<div class="card">
				<div class="image">
					<img src="{{ $photo->filePath }}">
				</div>
				<div class="content">
					<div class="limited description">
						{{ $photo->trimmedDescription }}
					</div>
				</div>
				<div class="extra content">
					<div class="right floated">
						@if(!$photo->is_public)
						<span class="ui red"><i class="minus circle icon"></i>This photo is private | </span>
						@endif
						<span title="{{ $photo->created_at }}">{{ $photo->uploaded }}</span>
					</div>
				</div>
				<div class="ui bottom attached buttons">
					<a href="{{ route("photo", [$photo->user->name, $photo->id]) }}" class="ui blue button">
						<i class="picture outline icon"></i>
						show
					</a>
					<div class="or"></div>
					<delete-photo-button photo-id="{{ $photo->id }}"></delete-photo-button>
				</div>
			</div>
		@endforeach
	</div>

	<delete-photo-modal attempt-url="{{ route("photo.upload.post") }}"></delete-photo-modal>

@endsection

resources/views/photos/notfound.blade.php
@extends("layout/root")

@section("styles")
	<link rel="stylesheet" type="text/css" href="{{ asset("css/photo.css") }}">
@endsection

@section("header")
	@include("layout.header")
@endsection

@section("content")
	<div class="ui vertical stripe segment">
		<div class="ui middle aligned stackable grid container center aligned">
			<h1>File not found.</h1>
		</div>
	</div>
@endsection

resources/views/photos/photo.blade.php
@extends("layout/root")

@section("styles")
	<link rel="stylesheet" type="text/css" href="{{ asset("css/photo.css") }}">
@endsection

@section("header")
	@include("layout.header")
@endsection

@section("content")
	<div class="ui vertical stripe segment">
		<div class="ui middle aligned container">

			<div class="ui raised centered card" style="min-width: 720px">
				<div class="image">
					<img src="{{ $photo->filePath }}">
				</div>
				<div class="extra content">
					<p class="photo description">{{ $photo->description }}</p>
				</div>
				@if($photo->tags->count())
					<div class="extra content">
						<div class="right floated author">
							<div class="ui small tag labels">
							@foreach($photo->tags as $tag)
								<span class="ui label"><i class="hashtag icon"></i>{{ $tag->name }}</span>
							@endforeach
							</div>
						</div>
					</div>
				@endif
				@if(!$photo->is_public)
					<div class="extra content">
						<div class="right floated author">
							<span class="ui red"><i class="minus circle icon"></i>This photo is private</span>
						</div>
					</div>
				@endif
				<div class="extra content">
					<div class="right floated author">
						<span title="{{ $photo->created_at }}">{{ $photo->uploaded }}</span>
						<img class="ui avatar spaced image" src="{{ $user->gravatar }}">
						&#64;{{ $user->name }}
					</div>
				</div>
			</div>

		</div>
	</div>
@endsection

resources/views/photos/table.blade.php
@extends("layout/dashboard")

@section("dashboard-content")

	<div class="ui switch layout segment clearing">
		<a href="{{ route("photos.grid") }}" class="ui labeled icon right floated button">
			<i class="block layout icon"></i>
			switch do grid view
		</a>
	</div>

	<table class="ui celled padded table">
		<thead>
			<tr>
				<th class="collapsing">Thumbnail</th>
				<th>Description &amp; Tags</th>
				<th class="collapsing single line">Is public?</th>
				<th class="collapsing single line">Uploaded at</th>
				<th class="collapsing single line action buttons cell">
					<a href="{{ route("photo.upload.form") }}" class="ui green small icon labeled fluid button">
						<i class="plus icon"></i>
						upload new
					</a>
				</th>
			</tr>
		</thead>
		<tbody>
			@foreach($photos as $photo)
				<tr>
					<td class="collapsing">
						<img src="{{ $photo->filePath }}" class="ui small rounded image">
					</td>
					<td>
						{{ $photo->trimmedDescription }}
						<div class="ui small tag labels">
							@foreach($photo->tags as $tag)
								<span class="ui label">{{ $tag->name }}</span>
							@endforeach
						</div>
					</td>
					<td>
						@if($photo->is_public)
							<i class="large green check icon"></i>
						@else
							<i class="large red close icon"></i>
						@endif
					</td>
					<td class="single line">
						{{ $photo->created_at }}<br>
						{{ $photo->uploaded }}
					</td>
					<td class="single line action buttons cell">
						<a href="{{ route("photo", [$photo->user->name, $photo->id]) }}" class="ui blue small icon labeled fluid button">
							<i class="picture outline icon"></i>
							show
						</a>
						<delete-photo-button class="small icon labeled fluid"></delete-photo-button>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>

	<delete-photo-modal attempt-url="{{ route("photo.upload.post") }}"></delete-photo-modal>

@endsection

resources/views/photos/upload.blade.php
@extends("layout/dashboard")

@section("dashboard-content")

	<upload-photo-form attempt-url="{{ route("photo.upload.post") }}" tag-url="{{ route("tag.all") }}"></upload-photo-form>

@endsection